CREATE TABLE users(userid INT,name VARCHAR(255) NOT NULL, PRIMARY KEY(userid));
CREATE TABLE movies(movieid INT,title VARCHAR(255) NOT NULL, PRIMARY KEY(movieid));
CREATE TABLE taginfo(tagid INT, content VARCHAR(255) NOT NULL, PRIMARY KEY(tagid));
CREATE TABLE genres(genreid INT, name VARCHAR(255) NOT NULL, PRIMARY KEY(genreid));
CREATE TABLE ratings(userid INT NOT NULL, movieid INT NOT NULL, rating NUMERIC(2,1) CHECK (rating >=0 AND rating <=5) NOT NULL, timestamp BIGINT NOT NULL, PRIMARY KEY(userid,movieid), FOREIGN KEY(movieid) REFERENCES movies ON DELETE CASCADE, FOREIGN KEY(userid) REFERENCES users ON DELETE CASCADE);
CREATE TABLE tags(userid INT NOT NULL,movieid INT NOT NULL,tagid INT NOT NULL,timestamp BIGINT NOT NULL, PRIMARY KEY(userid,movieid,tagid), FOREIGN KEY(userid) REFERENCES users ON DELETE CASCADE, FOREIGN KEY(movieid) REFERENCES movies ON DELETE CASCADE, FOREIGN KEY(tagid) REFERENCES taginfo ON DELETE CASCADE);
CREATE TABLE hasagenre(movieid INT NOT NULL, genreid INT NOT NULL, PRIMARY KEY(movieid,genreid), FOREIGN KEY(movieid) REFERENCES movies ON DELETE CASCADE, FOREIGN KEY(genreid) REFERENCES genres ON DELETE CASCADE);